"""Add content_type and attachments

Revision ID: 107e3e8bbcdc
Revises: 3b4c625bc137
Create Date: 2024-12-30 17:33:20.669340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107e3e8bbcdc'
down_revision = '3b4c625bc137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('chat_message_id', sa.Integer(), nullable=True),
    sa.Column('discussion_post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['discussion_post_id'], ['discussion_posts.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=20), nullable=True))

    with op.batch_alter_table('discussion_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=20), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('content_type')

    with op.batch_alter_table('discussion_posts', schema=None) as batch_op:
        batch_op.drop_column('content_type')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('content_type')

    op.drop_table('attachments')
    # ### end Alembic commands ###
