"""update assignment submission fields

Revision ID: 1535e19cb0f7
Revises: b5f9709c0298
Create Date: 2024-12-26 05:32:56.712488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1535e19cb0f7'
down_revision = 'b5f9709c0298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('graded_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('submission_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('graded_at')
        batch_op.drop_column('submitted_at')

    # ### end Alembic commands ###
