"""Add semester and module goals tables

Revision ID: 3773a1541aed
Revises: f1200640083a
Create Date: 2024-12-30 18:13:56.049115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3773a1541aed'
down_revision = 'f1200640083a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semester_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=False),
    sa.Column('target_gpa', sa.Float(), nullable=False),
    sa.Column('current_gpa', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_goal_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('target_grade', sa.Float(), nullable=False),
    sa.Column('current_grade', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['semester_goal_id'], ['semester_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_goals')
    op.drop_table('semester_goals')
    # ### end Alembic commands ###
