"""add status field to course model

Revision ID: 395e00dfb5aa
Revises: 870630b06a22
Create Date: 2024-12-26 16:08:38.804039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395e00dfb5aa'
down_revision = '870630b06a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
