"""rename sent_at to timestamp in messages table

Revision ID: 3b4c625bc137
Revises: d8740072505f
Create Date: 2024-12-29 07:26:26.511466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4c625bc137'
down_revision = 'd8740072505f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('read_timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_column('read_at')

    # ### end Alembic commands ###
