"""add course_id to academic goals

Revision ID: 61db7610565d
Revises: 2e878ba6785e
Create Date: 2024-12-26 05:43:02.601194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61db7610565d'
down_revision = '2e878ba6785e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_academic_goals_course_id', 'courses', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_goals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_academic_goals_course_id', type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
