"""add grade weights to course model

Revision ID: 6ca76312169d
Revises: 61db7610565d
Create Date: 2024-12-26 05:45:03.278957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca76312169d'
down_revision = '61db7610565d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignments_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('midterm_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('final_weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('final_weight')
        batch_op.drop_column('midterm_weight')
        batch_op.drop_column('assignments_weight')

    # ### end Alembic commands ###
