"""add program_id to user model

Revision ID: 7ad494f5be8d
Revises: c8df60cb59fd
Create Date: 2024-12-26 02:03:37.508862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad494f5be8d'
down_revision = 'c8df60cb59fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_program_id', 'program', ['program_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_program_id', type_='foreignkey')
        batch_op.drop_column('program_id')

    # ### end Alembic commands ###
