"""add semester field to course model

Revision ID: 870630b06a22
Revises: 6ca76312169d
Create Date: 2024-12-26 15:56:18.263722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870630b06a22'
down_revision = '6ca76312169d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('semester')

    # ### end Alembic commands ###
