"""add semester and academic_year to academic records

Revision ID: 93a0f1adf575
Revises: 395e00dfb5aa
Create Date: 2024-12-26 16:15:14.452199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a0f1adf575'
down_revision = '395e00dfb5aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('academic_year', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_records', schema=None) as batch_op:
        batch_op.drop_column('academic_year')
        batch_op.drop_column('semester')

    # ### end Alembic commands ###
