"""add embedding columns for semantic search

Revision ID: a01dff589309
Revises: b85f82c21993
Create Date: 2025-05-17 18:07:58.271867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01dff589309'
down_revision = 'b85f82c21993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', sa.PickleType(), nullable=True))

    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    with op.batch_alter_table('course_materials', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
