"""add quiz and communication models

Revision ID: b5f9709c0298
Revises: 7ad494f5be8d
Create Date: 2024-12-26 02:59:29.311161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f9709c0298'
down_revision = '7ad494f5be8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_message_timestamp')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('read_timestamp')
        batch_op.drop_column('body')
        batch_op.drop_column('read')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('body')
        batch_op.drop_column('priority')
        batch_op.drop_column('category')
        batch_op.drop_column('read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('body', sa.TEXT(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('message')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('body', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('read_timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_message_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('read_at')
        batch_op.drop_column('sent_at')
        batch_op.drop_column('content')
        batch_op.drop_column('subject')

    op.drop_table('quiz_submission')
    op.drop_table('quiz')
    op.drop_table('announcement')
    # ### end Alembic commands ###
