"""Add FAQ model

Revision ID: b85f82c21993
Revises: 3cdd17c74a2c
Create Date: 2025-05-17 16:12:14.967763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85f82c21993'
down_revision = '3cdd17c74a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('policies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('assignment_late_penalty', sa.FLOAT(), nullable=True),
    sa.Column('minimum_passing_grade', sa.FLOAT(), nullable=True),
    sa.Column('attendance_requirement', sa.FLOAT(), nullable=True),
    sa.Column('grade_scale', sa.VARCHAR(length=20), nullable=True),
    sa.Column('allow_resubmissions', sa.BOOLEAN(), nullable=True),
    sa.Column('max_resubmissions', sa.INTEGER(), nullable=True),
    sa.Column('notification_lead_time', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('faqs')
    # ### end Alembic commands ###
